# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 22:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20, verbose_name='\u6807\u9898')),
                ('button', models.CharField(default='', max_length=50, verbose_name='\u6309\u94ae')),
                ('img', models.ImageField(upload_to='text_img/%Y/%m', verbose_name='\u6587\u7ae0\u56fe\u7247')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8f6e\u64ad\u56fe',
                'verbose_name_plural': '\u8f6e\u64ad\u56fe',
            },
        ),
    ]
