# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_narration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='narration',
            options={'verbose_name': '\u53d9\u8ff0', 'verbose_name_plural': '\u53d9\u8ff0'},
        ),
    ]
