# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.CharField(default='', max_length=20, verbose_name='\u6807\u9898')),
                ('img', models.ImageField(upload_to='comic_img/%Y/%m', verbose_name='\u6587\u7ae0\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u52a8\u6f2b',
                'verbose_name_plural': '\u52a8\u6f2b',
            },
        ),
    ]
