# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171202_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.CharField(default='', max_length=20, verbose_name='\u6807\u9898')),
                ('img', models.ImageField(upload_to='make_img/%Y/%m', verbose_name='\u6587\u7ae0\u56fe\u7247')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
            ],
            options={
                'verbose_name': '\u5236\u4f5c',
                'verbose_name_plural': '\u5236\u4f5c',
            },
        ),
    ]
